name: GitHub Actions CI

# Cache is used for all Windows and macOS dependencies (size approx. 1230 * 2 + 1850 = 4310 MiB)
# Cache is not used for Ubuntu builds, because it already has all dependencies except
# the appropriate libtorrent version, which only takes 3-5 minutes to build from source anyway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]
  release:
    types: # This configuration does not affect the page_build event above
      - created
env:
  VCPKG_COMMIT: e4ce66eecfd3e5cca5eac06c971921bf8e37cf88
  VCPKG_DEST_MACOS: /Users/runner/qbt_tools/vcpkg
  VCPKG_DEST_WIN: C:\qbt_tools\vcpkg
  LIBTORRENT_VERSION_TAG: v1.2.12

jobs:
  ci_macos:
    name: macOS + vcpkg

    strategy:
      matrix:
        qbt_gui: ["GUI=OFF"]
      fail-fast: false

    runs-on: macos-10.15

    defaults:
      run:
        shell: pwsh

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    # - ninja is needed for building qBittorrent (because it's preferrable, not a hard requirement)
    # - automake is needed for the installation the vcpkg installation of fontconfig, a dependency of qt5-base
    - name: install additional required packages with homebrew
      shell: bash
      run: |
        brew install automake ninja

    - name: setup vcpkg (cached, if possible)
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgDirectory: ${{ env.VCPKG_DEST_MACOS }}
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT }}
        setupOnly: true

    - name: configure vcpkg triplet overlay for release builds only
      run: |
        New-Item -Path ${{ github.workspace }} -Name "triplets_overlay" -ItemType Directory
        Copy-Item ${{ env.RUNVCPKG_VCPKG_ROOT }}/triplets/x64-osx.cmake `
          ${{ github.workspace }}/triplets_overlay/x64-osx-release.cmake
        Add-Content ${{ github.workspace }}/triplets_overlay/x64-osx-release.cmake `
          -Value "set(VCPKG_BUILD_TYPE release)","set(VCPKG_OSX_DEPLOYMENT_TARGET 10.15)"

    - name: install dependencies via vcpkg
      run: |
        $packages = `
          "boost-circular-buffer:x64-osx-release",
          "libtorrent:x64-osx-release",
          "qt5-base:x64-osx-release",
          "qt5-svg:x64-osx-release",
          "qt5-tools:x64-osx-release",
          "qt5-macextras:x64-osx-release"
        ${{ env.RUNVCPKG_VCPKG_ROOT }}/vcpkg upgrade `
            --overlay-triplets=${{ github.workspace }}/triplets_overlay `
            --overlay-ports=${{ github.workspace }}/vcpkg `
            --no-dry-run
        foreach($package in $packages)
        {
          ${{ env.RUNVCPKG_VCPKG_ROOT }}/vcpkg install $package `
            --overlay-triplets=${{ github.workspace }}/triplets_overlay `
            --overlay-ports=${{ github.workspace }}/vcpkg `
            --clean-after-build
        }

    - name: build qBittorrent
      shell: bash
      run: |
        cmake -B build -G "Ninja" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_DEST_MACOS }}/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=x64-osx-release \
          -D${{ matrix.qbt_gui }} \
          -DVERBOSE_CONFIGURE=ON \
          --graphviz=build/target_graph.dot
        cmake --build build

    - name: upload artifact as zip
      uses: actions/upload-artifact@v2
      with:
        name: qBittorrent-CI_macOS_${{ matrix.qbt_gui }}
        path: |
          build/compile_commands.json
          build/target_graph.dot
          build/qbittorrent.app
          build/qbittorrent-nox.app
